### ISSUE TITLE
Am i stupid or is something broken?

### ISSUE THREAD

**Issue by BluCobalt** [EmotionalLove/ReChatBridge#1]
My error: https://pastebin.com/PzriKzYn
I also tried (re) compiling re:minecraft but i couldnt, so i just used the latest release.
heres the jar i built: https://i.blucobalt.dev/rechatbridge-1.0-SNAPSHOT.jar
One more thing, are there no releases because this isnt in a usable state?
probs just because that^
thx

**Comment by EmotionalLove** [comment]
don’t compile with gradle, it doesn’t pack the libraries it needs in.

compile with intellijs artifact manager and make sure plugin.yml is included in the jar and bettercommandsystem is extracted into the jar

**Comment by BluCobalt** [comment]
That worked, thanks
